
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAppCargadorRips.EF_Models
{

using System;
    using System.Collections.Generic;
    
public partial class Administradora
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Administradora()
    {

        this.Servicio_Validacion = new HashSet<Servicio_Validacion>();

        this.MSYPS_Consulta = new HashSet<MSYPS_Consulta>();

        this.SDS_Consulta = new HashSet<SDS_Consulta>();

        this.SDS_Factura = new HashSet<SDS_Factura>();

        this.SDS_Hospitalizacion = new HashSet<SDS_Hospitalizacion>();

        this.SDS_Medicamento = new HashSet<SDS_Medicamento>();

        this.SDS_Otro_Servicio = new HashSet<SDS_Otro_Servicio>();

        this.SDS_Procedimiento = new HashSet<SDS_Procedimiento>();

        this.SDS_Recien_Nacido = new HashSet<SDS_Recien_Nacido>();

        this.SDS_Urgencia = new HashSet<SDS_Urgencia>();

    }


    public long administradora_id { get; set; }

    public string codigo { get; set; }

    public string nombre { get; set; }

    public bool habilitada { get; set; }

    public bool contributivo { get; set; }

    public bool subsidiado { get; set; }

    public bool vinculado { get; set; }

    public bool particular { get; set; }

    public bool otro { get; set; }

    public System.DateTime fecha_modificacion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Servicio_Validacion> Servicio_Validacion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MSYPS_Consulta> MSYPS_Consulta { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SDS_Consulta> SDS_Consulta { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SDS_Factura> SDS_Factura { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SDS_Hospitalizacion> SDS_Hospitalizacion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SDS_Medicamento> SDS_Medicamento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SDS_Otro_Servicio> SDS_Otro_Servicio { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SDS_Procedimiento> SDS_Procedimiento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SDS_Recien_Nacido> SDS_Recien_Nacido { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SDS_Urgencia> SDS_Urgencia { get; set; }

}

}
