//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administradora
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Administradora()
        {
            this.Servicio_Validacion = new HashSet<Servicio_Validacion>();
        }
    
        public long administradora_id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public bool habilitada { get; set; }
        public bool contributivo { get; set; }
        public bool subsidiado { get; set; }
        public bool vinculado { get; set; }
        public bool particular { get; set; }
        public bool otro { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio_Validacion> Servicio_Validacion { get; set; }
    }
}
