
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAppCargadorRips.EF_Models
{

using System;
    using System.Collections.Generic;
    
public partial class Cargador_Rips
{

    public long configuracion_cargador_id { get; set; }

    public string directorio_zip { get; set; }

    public string usuario_directorio_zip { get; set; }

    public string contraseña_directorio_zip { get; set; }

    public string contraseña_autorizacion { get; set; }

}

}
