//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIE10
    {
        public long cie10_id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public long sexo_id { get; set; }
        public short edad_minima_años { get; set; }
        public short edad_maxima_años { get; set; }
        public int edad_minima_dias { get; set; }
        public int edad_maxima_dias { get; set; }
        public bool mortalidad { get; set; }
        public bool morbilidad { get; set; }
        public string categoria { get; set; }
        public string clase { get; set; }
        public byte numero_capitulo { get; set; }
        public string capitulo { get; set; }
        public string agrupacion1 { get; set; }
        public string codigo_agrupacion2 { get; set; }
        public string agrupacion2 { get; set; }
        public string causas { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public bool cie10_2002 { get; set; }
        public bool cie10_2005 { get; set; }
        public bool cie10_2009 { get; set; }
        public bool cie10_2012 { get; set; }
        public bool cie10_2014 { get; set; }
    
        public virtual Sexo Sexo { get; set; }
    }
}
