//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUPS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUPS()
        {
            this.MSYPS_Consulta = new HashSet<MSYPS_Consulta>();
            this.SDS_Consulta = new HashSet<SDS_Consulta>();
            this.SDS_Procedimiento = new HashSet<SDS_Procedimiento>();
        }
    
        public long cups_id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public long sexo_id { get; set; }
        public short edad_minima_años { get; set; }
        public short edad_maxima_años { get; set; }
        public int edad_minima_dias { get; set; }
        public int edad_maxima_dias { get; set; }
        public Nullable<byte> maximo_veces_dia { get; set; }
        public Nullable<byte> maximo_veces_vida { get; set; }
        public Nullable<short> tiempoLimiteDias { get; set; }
        public bool quirurgico { get; set; }
        public string tipo_atencion { get; set; }
        public string tipo_procedimiento { get; set; }
        public byte num_seccion { get; set; }
        public string seccion { get; set; }
        public byte numero_grupo { get; set; }
        public string grupo { get; set; }
        public string subgrupo { get; set; }
        public string categoria { get; set; }
        public string subcategoria { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public bool cups2007_4905 { get; set; }
        public bool pos2010_008 { get; set; }
        public bool pos2012_029 { get; set; }
        public bool pos2014_5521 { get; set; }
        public bool cups2016_4678_1352 { get; set; }
        public bool pos2016_5592 { get; set; }
        public bool cups2017_1132 { get; set; }
        public bool pos2017_6408_1687 { get; set; }
        public bool cups2018_5171_483 { get; set; }
    
        public virtual Sexo Sexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSYPS_Consulta> MSYPS_Consulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SDS_Consulta> SDS_Consulta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SDS_Procedimiento> SDS_Procedimiento { get; set; }
    }
}
