
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAppCargadorRips.EF_Models
{

using System;
    using System.Collections.Generic;
    
public partial class Errores_Usuario
{

    public string tip_ide { get; set; }

    public string num_ide { get; set; }

    public string apellido_a { get; set; }

    public string apellido_b { get; set; }

    public string nombre_a { get; set; }

    public string nombre_b { get; set; }

    public string sexo { get; set; }

    public string consecutivo { get; set; }

    public string ErrorCode { get; set; }

    public string ErrorColumn { get; set; }

    public string error { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

}

}
