//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Errores_Factura
    {
        public string cod_pre { get; set; }
        public string num_fac { get; set; }
        public string fec_exp { get; set; }
        public string fec_inc { get; set; }
        public string fec_fin { get; set; }
        public string cod_ent { get; set; }
        public string num_con { get; set; }
        public string plan_ben { get; set; }
        public string num_poli { get; set; }
        public string val_copa { get; set; }
        public string val_com { get; set; }
        public string val_desc { get; set; }
        public string val_net { get; set; }
        public string consecutivo { get; set; }
        public string radicado { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorColumn { get; set; }
        public string error { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    }
}
