//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Errores_Consulta
    {
        public string num_fac { get; set; }
        public string cod_pre { get; set; }
        public string tip_ide { get; set; }
        public string num_ide { get; set; }
        public Nullable<System.DateTime> fec_cons { get; set; }
        public string num_aut { get; set; }
        public string cod_proced { get; set; }
        public string finali_con { get; set; }
        public string cau_ext { get; set; }
        public string cdiag_pri { get; set; }
        public string cdiag_r1 { get; set; }
        public string cdiag_r2 { get; set; }
        public string cdiag_r3 { get; set; }
        public string tip_diag_p { get; set; }
        public string val_cons { get; set; }
        public string val_cuo_mo { get; set; }
        public string val_net { get; set; }
        public string cod_adm { get; set; }
        public string tu { get; set; }
        public string edad { get; set; }
        public string med_edad { get; set; }
        public string genero { get; set; }
        public string depto { get; set; }
        public string munic { get; set; }
        public string radicado { get; set; }
        public Nullable<System.DateTime> fechaplano { get; set; }
        public string consecutivo { get; set; }
        public string usu_nvo { get; set; }
        public string tipoRed { get; set; }
        public string apellido_a { get; set; }
        public string nombre_a { get; set; }
        public string zona_res { get; set; }
        public string genero_actualizado { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorColumn { get; set; }
        public string error { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    }
}
