
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAppCargadorRips.EF_Models
{

using System;
    using System.Collections.Generic;
    
public partial class Errores_Otro_Servicio
{

    public string num_fac { get; set; }

    public string cod_pre { get; set; }

    public string tip_ide { get; set; }

    public string num_ide { get; set; }

    public string num_aut { get; set; }

    public string tip_serv { get; set; }

    public string cod_serv { get; set; }

    public string nom_serv { get; set; }

    public string cantidad { get; set; }

    public string val_uni_in { get; set; }

    public string val_tot_in { get; set; }

    public string cod_adm { get; set; }

    public Nullable<System.DateTime> fecha_convert { get; set; }

    public string tu { get; set; }

    public string edad { get; set; }

    public string med_edad { get; set; }

    public string genero { get; set; }

    public string depto { get; set; }

    public string munic { get; set; }

    public string radicado { get; set; }

    public Nullable<System.DateTime> fechaplano { get; set; }

    public string consecutivo { get; set; }

    public string usu_nvo { get; set; }

    public string tipoRed { get; set; }

    public string apellido_a_fonetico { get; set; }

    public string nombre_a_fonetico { get; set; }

    public string zona_res { get; set; }

    public string genero_actualizado { get; set; }

    public string ErrorCode { get; set; }

    public string ErrorColumn { get; set; }

    public string error { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

}

}
