
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAppCargadorRips.EF_Models
{

using System;
    using System.Collections.Generic;
    
public partial class Estado_RIPS
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Estado_RIPS()
    {

        this.Radicacion = new HashSet<Radicacion>();

        this.Radicacion1 = new HashSet<Radicacion>();

        this.Servicio_Validacion = new HashSet<Servicio_Validacion>();

        this.Acto_Quirurgico = new HashSet<Acto_Quirurgico>();

        this.Ambito_Procedimiento = new HashSet<Ambito_Procedimiento>();

        this.Año_Permitido = new HashSet<Año_Permitido>();

        this.Categoria = new HashSet<Categoria>();

        this.Causa_Externa = new HashSet<Causa_Externa>();

        this.Control_Prenatal = new HashSet<Control_Prenatal>();

        this.Destino_Salida = new HashSet<Destino_Salida>();

        this.Estado_Salida = new HashSet<Estado_Salida>();

        this.Estructura = new HashSet<Estructura>();

        this.Estructura_Campo = new HashSet<Estructura_Campo>();

        this.Finalidad_Consulta = new HashSet<Finalidad_Consulta>();

        this.Finalidad_Procedimiento = new HashSet<Finalidad_Procedimiento>();

        this.Personal_Atiende = new HashSet<Personal_Atiende>();

        this.Sexo = new HashSet<Sexo>();

        this.Tipo_Diagnostico = new HashSet<Tipo_Diagnostico>();

        this.Tipo_Identificacion = new HashSet<Tipo_Identificacion>();

        this.Tipo_Medicamento = new HashSet<Tipo_Medicamento>();

        this.Tipo_Servicio = new HashSet<Tipo_Servicio>();

        this.Tipo_Usuario = new HashSet<Tipo_Usuario>();

        this.Via_Ingreso = new HashSet<Via_Ingreso>();

        this.Zona_Residencia = new HashSet<Zona_Residencia>();

        this.Correo = new HashSet<Correo>();

        this.Correo1 = new HashSet<Correo>();

        this.Correo2 = new HashSet<Correo>();

        this.Web_Mensaje = new HashSet<Web_Mensaje>();

        this.Web_Permiso = new HashSet<Web_Permiso>();

        this.Web_Permiso1 = new HashSet<Web_Permiso>();

        this.Web_Permiso2 = new HashSet<Web_Permiso>();

        this.Web_Rol = new HashSet<Web_Rol>();

        this.Web_Rol1 = new HashSet<Web_Rol>();

        this.Web_Rol2 = new HashSet<Web_Rol>();

        this.Web_RolHasPermiso = new HashSet<Web_RolHasPermiso>();

        this.Web_RolHasPermiso1 = new HashSet<Web_RolHasPermiso>();

        this.Web_RolHasPermiso2 = new HashSet<Web_RolHasPermiso>();

        this.Plantilla_Correo = new HashSet<Plantilla_Correo>();

        this.Plantilla_Correo1 = new HashSet<Plantilla_Correo>();

        this.Plantilla_Correo2 = new HashSet<Plantilla_Correo>();

        this.Web_Pregunta_Frecuente = new HashSet<Web_Pregunta_Frecuente>();

        this.Web_Pregunta_Frecuente1 = new HashSet<Web_Pregunta_Frecuente>();

        this.Web_Pregunta_Frecuente2 = new HashSet<Web_Pregunta_Frecuente>();

        this.Web_Usuario = new HashSet<Web_Usuario>();

        this.Web_Usuario1 = new HashSet<Web_Usuario>();

        this.Web_Usuario2 = new HashSet<Web_Usuario>();

        this.Web_Correo_Sin_Restriccion = new HashSet<Web_Correo_Sin_Restriccion>();

        this.Web_Administrador = new HashSet<Web_Administrador>();

        this.Web_Documento = new HashSet<Web_Documento>();

        this.Web_Validacion = new HashSet<Web_Validacion>();

        this.Web_Preradicacion = new HashSet<Web_Preradicacion>();

    }


    public long estado_rips_id { get; set; }

    public byte numero { get; set; }

    public string tipo { get; set; }

    public string nombre { get; set; }

    public string descripcion { get; set; }

    public string imagen { get; set; }

    public System.DateTime fecha_modificacion { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Radicacion> Radicacion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Radicacion> Radicacion1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Servicio_Validacion> Servicio_Validacion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Acto_Quirurgico> Acto_Quirurgico { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Ambito_Procedimiento> Ambito_Procedimiento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Año_Permitido> Año_Permitido { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Categoria> Categoria { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Causa_Externa> Causa_Externa { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Control_Prenatal> Control_Prenatal { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Destino_Salida> Destino_Salida { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Estado_Salida> Estado_Salida { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Estructura> Estructura { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Estructura_Campo> Estructura_Campo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Finalidad_Consulta> Finalidad_Consulta { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Finalidad_Procedimiento> Finalidad_Procedimiento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Personal_Atiende> Personal_Atiende { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sexo> Sexo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tipo_Diagnostico> Tipo_Diagnostico { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tipo_Identificacion> Tipo_Identificacion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tipo_Medicamento> Tipo_Medicamento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tipo_Servicio> Tipo_Servicio { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tipo_Usuario> Tipo_Usuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Via_Ingreso> Via_Ingreso { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Zona_Residencia> Zona_Residencia { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Correo> Correo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Correo> Correo1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Correo> Correo2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Mensaje> Web_Mensaje { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Permiso> Web_Permiso { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Permiso> Web_Permiso1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Permiso> Web_Permiso2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Rol> Web_Rol { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Rol> Web_Rol1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Rol> Web_Rol2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_RolHasPermiso> Web_RolHasPermiso { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_RolHasPermiso> Web_RolHasPermiso1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_RolHasPermiso> Web_RolHasPermiso2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Plantilla_Correo> Plantilla_Correo { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Plantilla_Correo> Plantilla_Correo1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Plantilla_Correo> Plantilla_Correo2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Pregunta_Frecuente> Web_Pregunta_Frecuente { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Pregunta_Frecuente> Web_Pregunta_Frecuente1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Pregunta_Frecuente> Web_Pregunta_Frecuente2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Usuario> Web_Usuario { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Usuario> Web_Usuario1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Usuario> Web_Usuario2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Correo_Sin_Restriccion> Web_Correo_Sin_Restriccion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Administrador> Web_Administrador { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Documento> Web_Documento { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Validacion> Web_Validacion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Web_Preradicacion> Web_Preradicacion { get; set; }

}

}
