
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAppCargadorRips.EF_Models
{

using System;
    using System.Collections.Generic;
    
public partial class Fallecidos
{

    public long fellecidos_id { get; set; }

    public string tipo_identificacion { get; set; }

    public string numero_identificacion { get; set; }

    public string apellido_a { get; set; }

    public string apellido_b { get; set; }

    public string nombre_a { get; set; }

    public string nombre_b { get; set; }

    public string sexo { get; set; }

    public Nullable<System.DateTime> fecha_defuncion { get; set; }

    public string tipo_muerte { get; set; }

    public Nullable<int> edad { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

}

}
