//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamento_ATC_Completo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicamento_ATC_Completo()
        {
            this.Medicamento_ATC_POS = new HashSet<Medicamento_ATC_POS>();
            this.Medicamento_CUM = new HashSet<Medicamento_CUM>();
        }
    
        public long medicamento_atc_completo_id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string cod_anatomico { get; set; }
        public string nom_anatomico { get; set; }
        public string cod_terapeutico { get; set; }
        public string nom_terapeutico { get; set; }
        public string cod_farmacologico { get; set; }
        public string nom_farmacologico { get; set; }
        public string cod_quimico { get; set; }
        public string nom_quimico { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicamento_ATC_POS> Medicamento_ATC_POS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicamento_CUM> Medicamento_CUM { get; set; }
    }
}
