//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamento_ATC_POS
    {
        public long medicamento_atc_pos_id { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string presentacion { get; set; }
        public string concentracion { get; set; }
        public Nullable<long> medicamento_atc_completo_id { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public bool pos2010_008 { get; set; }
        public bool pos2012_029 { get; set; }
        public bool pos2014_5521 { get; set; }
        public bool pos2015_5926 { get; set; }
        public bool pos2016_5592 { get; set; }
        public bool pos2017_6408 { get; set; }
    
        public virtual Medicamento_ATC_Completo Medicamento_ATC_Completo { get; set; }
    }
}
