//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamento_CUM
    {
        public long medicamento_cum_id { get; set; }
        public Nullable<long> codigo { get; set; }
        public string nombre { get; set; }
        public string fabricante { get; set; }
        public int expediente_CUM { get; set; }
        public short consecutivo { get; set; }
        public string descripcion { get; set; }
        public Nullable<long> medicamento_atc_completo_id { get; set; }
        public string via_administracion { get; set; }
        public string principio_activo { get; set; }
        public string unidad_medida { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string unidad_referencia { get; set; }
        public string forma_farmaceutica { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public Nullable<bool> cum_2018 { get; set; }
    
        public virtual Medicamento_ATC_Completo Medicamento_ATC_Completo { get; set; }
    }
}
