
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAppCargadorRips.EF_Models
{

using System;
    using System.Collections.Generic;
    
public partial class MSYPS_Consulta
{

    public long consulta_id { get; set; }

    public System.Guid rowguid { get; set; }

    public string numero_factura { get; set; }

    public long prestador_id { get; set; }

    public long usuario_id { get; set; }

    public System.DateTime fecha_consulta { get; set; }

    public long codigo_consulta_id { get; set; }

    public long finalidad_id { get; set; }

    public long causa_externa_id { get; set; }

    public long diagnostico_principal_id { get; set; }

    public Nullable<long> diagnostico_relacionado_1_id { get; set; }

    public Nullable<long> diagnostico_relacionado_2_id { get; set; }

    public Nullable<long> diagnostico_relacionado_3_id { get; set; }

    public Nullable<long> tipo_diagnostico_id { get; set; }

    public Nullable<decimal> valor_consulta { get; set; }

    public Nullable<decimal> valor_cuota { get; set; }

    public Nullable<decimal> valor_neto { get; set; }

    public long administradora_id { get; set; }

    public long tipo_usuario_id { get; set; }

    public byte edad { get; set; }

    public Nullable<long> med_edad_id { get; set; }

    public Nullable<long> divipola_id { get; set; }

    public string radicado { get; set; }

    public System.DateTime fecha_carga { get; set; }

    public System.DateTime fecha_modificacion { get; set; }



    public virtual Causa_Externa Causa_Externa { get; set; }

    public virtual Finalidad_Consulta Finalidad_Consulta { get; set; }

    public virtual Medida_Edad Medida_Edad { get; set; }

    public virtual Tipo_Diagnostico Tipo_Diagnostico { get; set; }

    public virtual Tipo_Usuario Tipo_Usuario { get; set; }

    public virtual Administradora Administradora { get; set; }

    public virtual CIE10 CIE10 { get; set; }

    public virtual CIE10 CIE101 { get; set; }

    public virtual CIE10 CIE102 { get; set; }

    public virtual CIE10 CIE103 { get; set; }

    public virtual CUPS CUPS { get; set; }

    public virtual DIVIPOLA DIVIPOLA { get; set; }

    public virtual Prestador Prestador { get; set; }

    public virtual SDS_Usuario SDS_Usuario { get; set; }

}

}
