//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poblacion_Especial
    {
        public long poblacion_especial_id { get; set; }
        public string tipo_identificacion { get; set; }
        public string numero_identificacion { get; set; }
        public byte codigo_poblacion { get; set; }
        public string nombre_poblacion { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    }
}
