//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDS_Medicamento
    {
        public long medicamento_id { get; set; }
        public System.Guid rowguid { get; set; }
        public long factura_id { get; set; }
        public long prestador_id { get; set; }
        public long usuario_id { get; set; }
        public System.DateTime fecha_medicamento { get; set; }
        public string numero_autorizacion { get; set; }
        public string codigo_medicamento { get; set; }
        public Nullable<long> medicamento_atc_completo_id { get; set; }
        public Nullable<long> medicamento_cum_id { get; set; }
        public long tipo_medicamento_id { get; set; }
        public string nombre_generico { get; set; }
        public string forma_farmaceutica { get; set; }
        public string concentracion { get; set; }
        public string unidad_medida { get; set; }
        public double numero_unidades { get; set; }
        public decimal valor_unitario { get; set; }
        public Nullable<decimal> valor_total { get; set; }
        public long administradora_id { get; set; }
        public long tipo_usuario_id { get; set; }
        public byte edad { get; set; }
        public Nullable<long> med_edad_id { get; set; }
        public Nullable<long> divipola_id { get; set; }
        public Nullable<long> zona_residencia_id { get; set; }
        public long radicacion_id { get; set; }
        public Nullable<long> tipo_usuario_nuevo_id { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    
        public virtual Radicacion Radicacion { get; set; }
        public virtual Medida_Edad Medida_Edad { get; set; }
        public virtual Tipo_Medicamento Tipo_Medicamento { get; set; }
        public virtual Tipo_Usuario Tipo_Usuario { get; set; }
        public virtual Tipo_Usuario Tipo_Usuario1 { get; set; }
        public virtual Zona_Residencia Zona_Residencia { get; set; }
        public virtual Administradora Administradora { get; set; }
        public virtual DIVIPOLA DIVIPOLA { get; set; }
        public virtual Medicamento_ATC_Completo Medicamento_ATC_Completo { get; set; }
        public virtual Medicamento_CUM Medicamento_CUM { get; set; }
        public virtual Prestador Prestador { get; set; }
        public virtual SDS_Factura SDS_Factura { get; set; }
        public virtual SDS_Usuario SDS_Usuario { get; set; }
    }
}
