//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sexo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sexo()
        {
            this.CIE10 = new HashSet<CIE10>();
            this.CUPS = new HashSet<CUPS>();
            this.SDS_Recien_Nacido = new HashSet<SDS_Recien_Nacido>();
            this.SDS_Usuario = new HashSet<SDS_Usuario>();
        }
    
        public long sexo_id { get; set; }
        public byte numero { get; set; }
        public string acronimo { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
        public long estado_rips_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CIE10> CIE10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUPS> CUPS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SDS_Recien_Nacido> SDS_Recien_Nacido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SDS_Usuario> SDS_Usuario { get; set; }
        public virtual Estado_RIPS Estado_RIPS { get; set; }
    }
}
