
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebAppCargadorRips.EF_Models
{

using System;
    using System.Collections.Generic;
    
public partial class SISBEN
{

    public long sisben_id { get; set; }

    public string tipo_identificacion { get; set; }

    public string numero_identificacion { get; set; }

    public string apellido_a { get; set; }

    public string apellido_b { get; set; }

    public string nombre_a { get; set; }

    public string nombre_b { get; set; }

    public string direccion { get; set; }

    public string localidad { get; set; }

    public string localidad_nombre { get; set; }

    public string nivel { get; set; }

    public string fecha_nacimiento { get; set; }

    public string fecha_encuesta { get; set; }

    public System.DateTime fecha_modificacion { get; set; }

}

}
