//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCargadorRips.EF_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Error
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_Error()
        {
            this.Servicio_Validacion_Error = new HashSet<Servicio_Validacion_Error>();
        }
    
        public long tipo_error_id { get; set; }
        public short numero { get; set; }
        public string nombre { get; set; }
        public string tipo_atencion { get; set; }
        public byte version_validador { get; set; }
        public System.DateTime fecha_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicio_Validacion_Error> Servicio_Validacion_Error { get; set; }
    }
}
